Repository compilerla/pems, pull requests merged in 2024-12, with the labels that each got.

#27 Fix: ignore .egg-info
  .dockerignore
Labels: bug

#30 CI: add code quality workflows
  .github/dependabot.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-triage.yml
  .github/workflows/labeler-actions.yml
  .github/workflows/labeler-docs.yml
Labels: actions

#32 Fix: correct org name in workflow
  .github/workflows/dependency-triage.yml
Labels: bug

#48 CI: publish docs preview site for PRs
  .github/workflows/mkdocs.yml
Labels: documentation, actions

#50 Fix: create pems/static folder for writing python packages
  .github/workflows/deploy.yml
Labels: bug

#46 Docs: getting started guide
  docs/.pages
  docs/development/README.md
  mkdocs.yml
Labels: documentation

#53 Docs: add product roadmap
  docs/README.md
Labels: documentation

#58 Fix: Docs site theme and Roadmap style
  docs/README.md
  docs/styles/theme.css
  mkdocs.yml
Labels: bug, documentation

#59 Fix: permissions for labeler jobs
  .github/workflows/dependency-triage.yml
  .github/workflows/labeler-actions.yml
  .github/workflows/labeler-docs.yml
Labels: bug
